# coding=utf-8
debug: true
mail:
    address: admin@gmail.com
    password: pwd
    smtp: smtp.gmail.com
    port: 587

user_password_salt: salt


mysql:
    user: root
    password: pwd
    host: localhost

redis:
    host: localhost
    port: 6379
